<?php

namespace QueueMaster\Utils;

/**
 * Minimal ULID generator for public identifiers exposed by the API.
 *
 * Output format:
 * - 26 chars
 * - Crockford Base32
 * - lexicographically sortable by creation time
 */
final class Ulid
{
    private const ENCODING = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

    /**
     * Generate a ULID string.
     */
    public static function generate(?int $timestampMs = null): string
    {
        $timestampMs ??= (int) floor(microtime(true) * 1000);

        if ($timestampMs < 0) {
            throw new \InvalidArgumentException('Timestamp must be positive');
        }

        return self::encodeTimestamp($timestampMs) . self::encodeRandom(random_bytes(10));
    }

    /**
     * Validate a ULID string generated by this helper.
     */
    public static function isValid(string $value): bool
    {
        return preg_match('/^[0-9A-HJKMNPQRSTVWXYZ]{26}$/', strtoupper($value)) === 1;
    }

    private static function encodeTimestamp(int $timestampMs): string
    {
        $encoded = '';
        $value = $timestampMs;

        for ($i = 0; $i < 10; $i++) {
            $index = $value % 32;
            $encoded = self::ENCODING[$index] . $encoded;
            $value = intdiv($value, 32);
        }

        return $encoded;
    }

    private static function encodeRandom(string $bytes): string
    {
        $value = 0;
        $bitCount = 0;
        $encoded = '';

        $length = strlen($bytes);
        for ($i = 0; $i < $length; $i++) {
            $value = ($value << 8) | ord($bytes[$i]);
            $bitCount += 8;

            while ($bitCount >= 5) {
                $bitCount -= 5;
                $index = ($value >> $bitCount) & 31;
                $encoded .= self::ENCODING[$index];
            }
        }

        if ($bitCount > 0) {
            $index = ($value << (5 - $bitCount)) & 31;
            $encoded .= self::ENCODING[$index];
        }

        return str_pad(substr($encoded, 0, 16), 16, '0');
    }
}
